package data;
// Generated 28 avr. 2015 13:05:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sc generated by hbm2java
 */
public class Sc  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set srs = new HashSet(0);
     private Set SScs = new HashSet(0);

    public Sc() {
    }

	
    public Sc(String name) {
        this.name = name;
    }
    public Sc(String name, Set srs, Set SScs) {
       this.name = name;
       this.srs = srs;
       this.SScs = SScs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getSrs() {
        return this.srs;
    }
    
    public void setSrs(Set srs) {
        this.srs = srs;
    }
    public Set getSScs() {
        return this.SScs;
    }
    
    public void setSScs(Set SScs) {
        this.SScs = SScs;
    }




}


