package data;
// Generated 26 avr. 2015 15:44:25 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Sr generated by hbm2java
 */
public class Sr  implements java.io.Serializable {


     private Integer id;
     private Qoso qoso;
     private S s;
     private Sc sc;
     private Sp sp;
     private String scName;
     private String SName;
     private String status;

    public Sr() {
    }

	
    public Sr(Qoso qoso, S s, Sc sc, Sp sp, String status) {
        this.qoso = qoso;
        this.s = s;
        this.sc = sc;
        this.sp = sp;
        this.status = status;
    }
    public Sr(Qoso qoso, S s, Sc sc, Sp sp, String scName, String SName, String status) {
       this.qoso = qoso;
       this.s = s;
       this.sc = sc;
       this.sp = sp;
       this.scName = scName;
       this.SName = SName;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Qoso getQoso() {
        return this.qoso;
    }
    
    public void setQoso(Qoso qoso) {
        this.qoso = qoso;
    }
    public S getS() {
        return this.s;
    }
    
    public void setS(S s) {
        this.s = s;
    }
    public Sc getSc() {
        return this.sc;
    }
    
    public void setSc(Sc sc) {
        this.sc = sc;
    }
    public Sp getSp() {
        return this.sp;
    }
    
    public void setSp(Sp sp) {
        this.sp = sp;
    }
    public String getScName() {
        return this.scName;
    }
    
    public void setScName(String scName) {
        this.scName = scName;
    }
    public String getSName() {
        return this.SName;
    }
    
    public void setSName(String SName) {
        this.SName = SName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Sr other = (Sr) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


