package data;
// Generated 28 avr. 2015 13:05:32 by Hibernate Tools 4.3.1



/**
 * SSc generated by hbm2java
 */
public class SSc  implements java.io.Serializable {


     private Integer id;
     private S s;
     private Sc sc;

    public SSc() {
    }

    public SSc(S s, Sc sc) {
       this.s = s;
       this.sc = sc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public S getS() {
        return this.s;
    }
    
    public void setS(S s) {
        this.s = s;
    }
    public Sc getSc() {
        return this.sc;
    }
    
    public void setSc(Sc sc) {
        this.sc = sc;
    }




}


